name: go
description: Go Mobile App
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ARCHITECTURE
  stacked: ^2.1.0
  stacked_services: ^0.8.3
  stacked_themes: ^0.3.2
  stacked_hooks: ^0.2.0
  flutter_hooks: ^0.16.0

  #HTTP REQUESTS
  http:

  #ADD CANCELLABLE ACTIONS TO ASYNC
  async:

  #FIRESTORE/FIREBASE
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  firebase_auth_oauth: ^1.0.1
  firebase_dynamic_links: ^2.0.2
  firebase_messaging: ^9.1.3
  firebase_storage: ^8.0.5
  cloud_functions: ^1.0.5
  cloud_firestore: ^1.0.7

  #Firebase
  #Firebase_Admob:

  #SOCIAL DEPENDENCIES
  google_sign_in: ^5.0.2
  flutter_facebook_auth: ^3.3.2+2

  #PHONE UTILITIES
  url_launcher: ^6.0.3
  share: ^2.0.1
  permission_handler: ^7.0.0
  app_settings: ^4.1.0
  flutter_local_notifications: ^5.0.0+4
  
  #LOCATION
  location: ^4.1.1
  geolocator: ^7.0.3
  geocode: ^1.0.1
  google_place: ^0.4.0
  google_maps_webservice: ^0.0.20-nullsafety.4
  google_maps_flutter: ^2.0.3
  maps_launcher: ^2.0.0

  #IMAGES
  cached_network_image: ^3.0.0
  image_cropper: ^1.4.0
  image_picker: ^0.7.4
  flutter_image_compress: ^1.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  image: ^3.0.2
  transparent_image: ^2.0.0

  #Youtube Videos
  youtube_player_flutter: ^8.0.0
  youtube_player_iframe: ^2.0.0
  

  #UI
  font_awesome_flutter: ^9.0.0
  shimmer: ^2.0.0


  #OTHER
  algolia: ^1.0.1
  flutter_typeahead: ^3.1.1
  intl_phone_field: ^2.0.0
  introduction_screen: ^2.1.0
  mailer: ^5.0.0




dev_dependencies:

#  flutter_launcher_icons: "^0.8.0"

  flutter_test:
    sdk: flutter

  build_runner:
  stacked_generator: ^0.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo3.png"
