name: go
description: Go Mobile App
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ARCHITECTURE
  stacked:
  stacked_services:
  stacked_themes:
  get_it:
  injectable:
  auto_route:

  #HTTP REQUESTS
  http:

  #ADD CANCELLABLE ACTIONS TO ASYNC
  async:

  #FIRESTORE DATABASE
  firebase_core:
  cloud_firestore:
  firebase_auth:
  firebase_storage:
  firebase_messaging: ^7.0.3
  firebase_dynamic_links:

  #Firebase
  firebase_admob:

  #SOCIAL DEPENDENCIES
  google_sign_in: ^4.0.11
  flutter_facebook_auth: ^2.0.0+1
  apple_sign_in: ^0.1.0

  #PHONE UTILITIES
  url_launcher:
  share:
  permission_handler:
  app_settings:
  
  #LOCATION
  location:
  geolocator:
  geocoder:
  flutter_google_places:
  flutter_google_places_api:
  google_maps_webservice:

  #IMAGES
  cached_network_image: ^2.5.0
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+21
  flutter_image_compress: ^0.7.0
  carousel_pro: ^1.0.0
  image: ^2.1.19

  #Youtube Videos
  youtube_player_flutter: ^7.0.0+7
  

  #UI
  font_awesome_flutter: 8.5.0
  shimmer: ^1.0.1
  adaptive_dialog: ^0.9.3

  #OTHER
  algolia: ^0.1.7
  flutter_typeahead: ^1.8.8
  intl_phone_field: ^1.4.2
  introduction_screen: ^1.0.7
  mailer: ^3.3.0
  provider: 
  



dev_dependencies:

  flutter_launcher_icons: "^0.8.0"

  flutter_test:
    sdk: flutter


  

  build_runner:
  auto_route_generator:
  injectable_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo3.png"
