name: go
description: Go Mobile App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ARCHITECTURE
  provider: ^4.3.2+2
  provider_architecture: ^1.1.1+1
  get_it: ^5.0.1

  #HTTP REQUESTS
  http: ^0.12.2

  #ADD CANCELLABLE ACTIONS TO ASYNC
  async: ^2.4.2

  #FIRESTORE DATABASE
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.3+1
  firebase_auth: ^0.18.3+1
  firebase_storage: ^5.1.0
  firebase_messaging: ^7.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
