enum BottomSheetType {
  imagePicker,
  causePublished,
  causeCreatorOptions,
  causeOptions,
  postPublished,
  postAuthorOptions,
  postOptions,
  currentUserOptions,
  userOptions,
  destructiveConfirmation,
  addContent,
  newContentConfirmation,
  addContentSuccessful,
  contentOptions,
  contentAuthorOptions,
}
